= XYZ Reader Starter Code

Udacity Android Developer Nanodegree - Projects 5: Make Your App Material

Improved the user experience of a news reading app using Material Design principles. Implimented use of Material Design UI standard components i.e. android design fundamentals, bold graphic design, fonts, color, adaptive design, meaningful motion, constrain layout and surfaces.

= Project Requirements

Uses Picasso, Picasso Pallette to display the Images and choose the color of the text view and textview bar according to the pallette of the image loaded.

Uses the Design Support library and its provided widget types (FloatingActionButton, AppBarLayout, SnackBar, etc).

Uses CoordinatorLayout for the main Activity.

App theme extends from AppCompat.

Uses an AppBar and associated Toolbars.

Uses provides a Floating Action Button for the most common action(s).

Application properly specifies elevations for app bars, FABs, and other elements specified in the Material Design specification.

Application provides sufficient spacing between elements.

Uses fonts that are the Android defaults.
